// 7가지 복합 신호 프리셋 정의
import { AlertPreset } from '../types/alert';

export const ALERT_PRESETS: AlertPreset[] = [
  {
    id: 'smart_money',
    name: '스마트머니 집결',
    description: '외국인+기관 동반 매수 + 저PBR',
    icon: '🎯',
    expectedFreq: '월 1~3회',
    reliability: 5,
    conditions: [
      { type: '외국인순매수', op: 'consecutive', days: 3 },
      { type: '기관순매수',   op: 'gte_amount' },
      { type: 'PBR',         op: 'lte_sector_ratio', ratio: 0.8 },
    ],
    logic: ['AND', 'AND'],
  },
  {
    id: 'momentum_explosion',
    name: '모멘텀 폭발',
    description: '체결강도 + 거래량 급증 + 외국인 매수',
    icon: '⚡',
    expectedFreq: '주 2~4회',
    reliability: 4,
    conditions: [
      { type: '체결강도', op: 'gte',            value: 140 },
      { type: '거래량',   op: 'gte_prev_ratio',  ratio: 2.0 },
      { type: '외국인순매수', op: 'gte_amount' },
    ],
    logic: ['AND', 'AND'],
  },
  {
    id: 'value_bottom',
    name: '가치 바닥 전환',
    description: 'PER+PBR+P/FCR 동시 저평가 + 외국인 전환',
    icon: '📊',
    expectedFreq: '월 1~2회',
    reliability: 5,
    conditions: [
      { type: 'PER',   op: 'lte_sector_ratio', ratio: 0.7 },
      { type: 'PBR',   op: 'lte_absolute',     value: 1.0 },
      { type: 'P/FCR', op: 'lte_sector_ratio', ratio: 0.7 },
      { type: '외국인순매수', op: 'turn_positive', days: 1 },
    ],
    logic: ['AND', 'AND', 'AND'],
  },
  {
    id: 'theme_entry',
    name: '테마 초입 포착',
    description: '업종 강세 + 체결강도 + 거래량',
    icon: '🔥',
    expectedFreq: '주 1~3회',
    reliability: 3,
    conditions: [
      { type: '업종지수', op: 'gte',            value: 2.0 },
      { type: '체결강도', op: 'gte',            value: 120 },
      { type: '거래량',   op: 'gte_prev_ratio', ratio: 1.5 },
    ],
    logic: ['AND', 'AND'],
  },
  {
    id: 'institution_leading',
    name: '기관 선행 매수',
    description: '기관 3일 연속 + 저PBR + 체결강도',
    icon: '🏦',
    expectedFreq: '월 2~4회',
    reliability: 4,
    conditions: [
      { type: '기관순매수', op: 'consecutive',      days: 3 },
      { type: 'PBR',       op: 'lte_sector_ratio', ratio: 0.9 },
      { type: '체결강도',  op: 'gte',              value: 110 },
    ],
    logic: ['AND', 'AND'],
  },
  {
    id: 'breakout_confirm',
    name: '고점 돌파 확인',
    description: '체결강도 + 거래량 + 외국인 + 아웃퍼폼',
    icon: '📈',
    expectedFreq: '주 1~2회',
    reliability: 4,
    conditions: [
      { type: '체결강도', op: 'gte',                value: 130 },
      { type: '거래량',   op: 'gte_avg20_ratio',    ratio: 1.8 },
      { type: '외국인순매수', op: 'gte_amount' },
      { type: '업종지수', op: 'outperform_kospi' },
    ],
    logic: ['AND', 'AND', 'AND'],
  },
  {
    id: 'oversold_reversal',
    name: '과매도 반등',
    description: '낙폭 과대 후 매수 전환 (역발상)',
    icon: '🔄',
    expectedFreq: '월 1~3회',
    reliability: 3,
    conditions: [
      { type: '체결강도',  op: 'gte',              value: 120 },
      { type: 'PBR',       op: 'lte_absolute',     value: 0.8 },
      { type: '외국인순매수', op: 'turn_positive', days: 1 },
      { type: '업종지수',  op: 'lte_5day_drop',    value: -5.0 },
    ],
    logic: ['AND', 'AND', 'AND'],
  },
];
